name: Make and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      -
        name: Make
        uses: heussd/opsify-logo@main
        with:
          run: |
            make
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{steps.date.outputs.date}}"
          prerelease: false
          title: "Release ${{steps.date.outputs.date}}"
          files: |
            *.png
